# Set compile options here

# Switch on debugging (yes|no)
# Debuggin on turns of optimization and turns on debugging information
# with -g while compiling and linking
DEBUG = no

# Switch on testversion (0|1)
# Testversion outputs a string (TESTVERSION) on each player's
# printout
TESTVERSION = 0

# Set languages to compile for. Currently available are english(en) and german(de)
LANGUAGES=de en
